
[wait time=200]
*start|スタート

[cm]

[position layer=message0 visible=false width=800 height=195 left=0 top=420 frame=MessageWindow2.png margint=40 marginb=20 marginl=60 marginr=20 ]
[position layer=message1 visible=false width=250 height=50 left=0 top=355 frame=NameWindow.png margint=13 marginb=0 marginl=60 marginr=0]
[position layer=message2 visible=false width=1 height=1 left=100 top=100 frame=ChoiceWindow.png margint=5 marginb=0 marginl=20 marginr=0]
[position layer=message3 visible=false width=250 height=50 left=100 top=200 frame=ChoiceWindow.png margint=5 marginb=0 marginl=20 marginr=0]


[backlay][image storage=sky.PNG page=back layer=base][trans method=crossfade time=1500][wt]
[position layer=message0 visible=true]
[position layer=message1 visible=true]
[delay speed=user]

[current layer=message0]我的前世是一只蚊子。[l][er][cm]
[current layer=message0]日复一日，刺破生灵的躯体，汲取血液，产下虫卵。[l][er][cm]
[current layer=message0]我生来就痴迷那种穿刺的触感。[l][er][cm]
[cm]
[current layer=message0]利刃般口器穿透皮肉、侵入温热躯体的滋味，时至今日依旧历历在目。[l][er][cm]
[backlay][image storage=room.PNG page=back layer=base][trans method=crossfade time=1500][wt][current layer=message1]柔肌 刺[current layer=message0]（人类要怎么做，才能再次体会那种感觉呢……）[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（好想再感受一次……）[l][er][cm]
[current layer=message0]叮咚——[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]来了！[l][er][cm]
[current layer=message0]思绪被门铃声打断，我连忙快步走向玄关。[l][er][cm]
[backlay][image storage=entrance.PNG page=back layer=base][trans method=crossfade time=1500][wt][current layer=message0]咔哒[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]不好意思久等啦，快进来坐。[l][er][cm]
[image layer=0 page=fore storage=default.png visible=true left=250][current layer=message1]河井 依子[current layer=message0]打扰啦～[l][er][cm]
[current layer=message0]我侧身让出道路，引她走进我的房间。[l][er][cm]
[backlay][image storage=room.PNG page=back layer=base][trans method=crossfade time=1500][wt][current layer=message1]柔肌 刺[current layer=message0]外面很热吧，喝点麦茶解暑。[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]谢谢你～[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]咕嘟、咕嘟、咕嘟，呼——活过来了！[l][er][cm]
[current layer=message0]晶莹汗珠顺着她白皙通透的脸颊滚落，她扬起一抹柔和笑意。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（肌肤真好看……）[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]真不错。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]对了，今天明明放假，你怎么还穿着校服？[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]今天有班委例会，暑假偶尔也要到校集合的。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]原来是这样，难得休息日还要忙活，辛苦啦……[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]不好意思，明知道你有事还约你出来，下次我会先问你有没有空再开口。[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]没关系，我想见你才愿意过来的。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]能听到你这么说，我真的很开心，谢谢你。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]啊，一直站着让你受累了，我房间很小没有多余椅子，随便找地方坐就好。[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]嗯，谢谢。[l][er][cm]
[current layer=message0]她环顾朴素狭小的房间，顺势坐到床边。[l][er][cm]
[current layer=message0]我也挨着她身侧坐下。[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]这里就是柔君的房间呀，你每天都睡在这张床上吗？[l][er][cm]
[current layer=message0]话音刚落，她直接往床上一倒，在床上滚来滚去。[l][er][cm]
[current layer=message0]可没过几秒，她猛地直起身。[l][er][cm]
[image layer=0 page=fore storage=awate.png visible=true left=215][current layer=message1]河井 依子[current layer=message0]啊！对不起！我穿外出的衣服直接躺，你会不会介意！[l][er][cm]
[current layer=message0]少女手足无措，满脸慌乱。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]完全不在意，你随便躺，就算直接在上面睡着也没关系。[l][er][cm]
[image layer=0 page=fore storage=tere.png visible=true left=215][current layer=message1]河井 依子[current layer=message0]谢、谢谢……？[l][er][cm]
[current layer=message0]她坐立难安，时不时偷瞄我一眼。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]依子，你还好吗？平时你都很沉稳，今天总觉得心神不宁的。[l][er][cm]
[image layer=0 page=fore storage=awate.png visible=true left=215][current layer=message1]河井 依子[current layer=message0]哎？没有！我很平静，完全没事！[l][er][cm]
[current layer=message0]我总觉得，她的脸颊比平日里染上了一层绯红。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]是不是发烧了？[l][er][cm]
[current layer=message0]我抬手想探她额头，她却下意识往后退了一步躲开。[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]没有发烧！我精神好得不得了！[l][er][cm]
[current layer=message0]她攥紧手臂做出充满活力的样子，这般俏皮模样我还是第一次见到。[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]大概是天太热，搞得我思绪乱糟糟的吧，哈哈……[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]乱糟糟？[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]不是！我不是那个意思！我说的不是那种奇怪的心情！[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]那种心情，指的是哪种？[l][er][cm]
[current layer=message1]河井 依子[current layer]诶！就是……那种暧昧的念头之类的……[l][er][cm]
[image layer=0 page=fore storage=tere.png visible=true left=215][current layer=message1]河井 依子[current layer=message0]可我们明明交往一整年了，柔君从来都不主动靠近我……[l][er][cm]
[image layer=0 page=fore storage=tere.png visible=true left=215][current layer=message1]河井 依子[current layer=message0]今天还是你第一次邀我来家里，我忍不住胡思乱想，会不会要发生什么……[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]想着想着，我就紧张到不行。[l][er][cm]
[current layer=message0]她眼尾泛起水光，垂下视线，眼看就要落下眼泪。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]可你来的时候看着和平常一模一样啊。[l][er][cm]
[image layer=0 page=fore storage=awate.png visible=true left=215][current layer=message1]河井 依子[current layer=message0]我一直在拼命忍耐！心脏砰砰跳个不停！[l][er][cm]
[current layer=message0]她伸手攥住我的手，按在自己胸口。[l][er][cm]
[image layer=0 page=fore storage=tere.png visible=true left=215][current layer=message1]河井 依子[current layer=message0]你听，心跳得这么快，对吧？[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]嗯……[l][er][cm]
[current layer=message0]若是以往，我定会慌乱不已、心头雀跃。可此刻不知为何，全身血液仿佛瞬间冻结，刺骨的冷意包裹着我。[l][er][cm]
[current layer=message0]冰冷之下，心底翻涌着一阵难以按捺的饥渴。[l][er][cm]
[current layer=message0]一种从未体会过、晦暗赤红的陌生欲望，在心底缓缓升腾。[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]柔君……[l][er][cm]
[current layer=message0]她轻轻一拽，我顺势俯身，将她压在了床上。[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]可以……吗？[l][er][cm]
[position layer=message2 visible=true]
[position layer=message3 visible=true]	
[current layer=message2]
[link target=*good]顺从她的心意行动[endlink]
[current layer=message3]
[link target=*bad]遵从内心的渴求[endlink]
[current layer=message0]
[s]
*good
[cm]
[image layer=0 page=fore storage=awate.png visible=false]
[position layer=message2 visible=false]
[position layer=message3 visible=false]	
[current layer=message0]
[current layer=message0]……[l][er][cm]
[current layer=message0]………[l][er][cm]
[current layer=message0]…………[l][er][cm]
[backlay][image storage=good.PNG page=back layer=base][trans method=crossfade time=1500][wt][current layer=message1]河井 依子[current layer=message0]嘿嘿……[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]真的、做到了呢……[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]是啊。[l][er][cm]
[current layer=message1]河井 依子[current layer]……[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]……[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]感觉……怎么样？[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]嗯……[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]特别美好。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（这和前世完全不是一个层次！！！）[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（根本没法相提并论！！！！！！！！）[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（原来人类男性的“穿刺”是这般滋味……太过震撼了）[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（而且可以反复、不停感受！做蚊子的时候一天最多三四次，产卵期间根本没法穿刺……）[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（生而为人真是太好了，我爱人类！）[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]我还以为你对我一点兴趣都没有，心里一直很不安……[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]怎么可能不在意，让你胡思乱想，对不起。[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]你一直都很珍惜我，刚刚也特别温柔。[l][er][cm]
[current layer=message0]少女脸颊染上薄红，羞涩地垂下脑袋。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]怎么了？[l][er][cm]
[current layer=message1]河井 依子[current layer=message0]我喜欢你。[l][er][cm]
[current layer=message0]她羞赧却满眼光亮，扬起灿烂的笑容望向我。[l][er][cm]
[current layer=message0]方才心底那股晦暗赤红的欲望，如同从未存在过一般消散无踪。[l][er][cm]
[current layer=message0]温柔平和的暖意填满了整个胸腔。[l][er][cm]
[current layer=message0]只想和眼前这个心爱之人，长久相伴下去。[l][er][cm]
[current layer=message0]我这般想着。[l][er][cm]
[position layer=message0  visible=false]
[position layer=message1 visible=false]
[position layer=message2 visible=false ]
[position layer=message3 visible=false]
[backlay][image storage=end.PNG page=back layer=base][trans method=crossfade time=1500][wt][l][er][cm]
[backlay][image storage=staff.PNG page=back layer=base][trans method=crossfade time=1500][wt][l][er][cm]
[jump storage=title.ks]
*bad
[image layer=0 page=fore storage=awate.png visible=false]
[cm]
[position layer=message2 visible=false]
[position layer=message3 visible=false]
[current layer=message0]
[current layer=message0]……[l][er][cm]
[current layer=message0]………[l][er][cm]
[current layer=message0]…………[l][er][cm]
[backlay][image storage=black.PNG page=back layer=base][trans method=crossfade time=1500][wt][current layer=message0]浑身燥热。[l][er][cm]
[current layer=message0]耳边只剩剧烈的心跳轰鸣。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（我刚刚……做了什么来着）[l][er][cm]
[current layer=message0]头痛欲裂。[l][er][cm]
[current layer=message0]头痛。[l][er][cm]
[current layer=message0]头痛难忍。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（手上湿漉漉的……）[l][er][cm]
[current layer=message0]视线落在自己双手，一种奇异温润触感残留其上。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（一片赤红……鲜艳刺目）[l][er][cm]
[current layer=message0]红色液体顺着指尖滴落，艳丽妖冶。[l][er][cm]
[current layer=message0]明明带着煽情的氛围，望着它心绪却奇异地平复下来。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（好暖……）[l][er][cm]
[current layer=message0]心底涌上想要不断触碰的渴求。[l][er][cm]
[backlay][image storage=bad.PNG page=back layer=base][trans method=crossfade time=1500][wt][current layer=message1]柔肌 刺[current layer=message0]（我想起来了……）[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（我再也按捺不住了……）[l][er][cm]
[current layer=message0]望着她如同淤塞水沟般瘫软的模样，心底自语。[l][er][cm]
[current layer=message0]（都怪依子，露出一副任人穿刺的模样……）[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]可她真的很美，是我见过最美的模样。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]依子……依子……[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]我喜欢你。[l][er][cm]
[current layer=message0]难以言喻的亢奋包裹住我的全身。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]原来人类的“穿刺”，是这般滋味。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]如今世的触感，和前世蚊子完全没有可比性。[l][er][cm]
[current layer=message0]方才她的神情、喘息、肌肤触感，尽数在脑海翻涌。[l][er][cm]
[current layer=message0]这是两世轮回里，我从未体会过的极致快感。[l][er][cm]
[current layer=message0]沉浸在幸福感中的时间转瞬即逝，我忽然意识到一件事。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]太可惜了。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]化为人形之后，我居然从没好好体会过，为什么呢。[l][er][cm]
[current layer=message0]将刺入的部分抽出，把脸颊埋进她柔软的小腹。[l][er][cm]
[current layer=message1]柔肌 刺[current layer=message0]（此刻我与她相融一体）[l][er][cm]
[current layer=message0]任由她流淌而出的温热尽数被我吞没。[l][er][cm]
[current layer=message0]感受着彼此交融的错觉。[l][er][cm]
[current layer=message0]我不停吞噬，直到心底的渴求彻底平息。[l][er][cm]

[position layer=message0  visible=false]
[position layer=message1 visible=false]
[position layer=message2 visible=false ]
[position layer=message3 visible=false]
[backlay][image storage=end.PNG page=back layer=base][trans method=crossfade time=1500][wt]
[l][er][cm]
[backlay][image storage=staff.PNG page=back layer=base][trans method=crossfade time=1500][wt]
[l][er][cm]
[jump storage=title.ks]
